# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edc_visit_schedule', '0001_initial'),
        ('edc_meta_data', '0001_initial'),
        ('edc_content_type_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labentry',
            name='visit_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edc_visit_schedule.VisitDefinition'),
        ),
        migrations.AddField(
            model_name='crfentry',
            name='content_type_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='edc_content_type_map.ContentTypeMap', verbose_name='entry form / model'),
        ),
        migrations.AddField(
            model_name='crfentry',
            name='visit_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edc_visit_schedule.VisitDefinition'),
        ),
        migrations.AlterUniqueTogether(
            name='labentry',
            unique_together=set([('visit_definition', 'requisition_panel')]),
        ),
        migrations.AlterUniqueTogether(
            name='crfentry',
            unique_together=set([('visit_definition', 'content_type_map')]),
        ),
    ]
