# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_meta_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crfentry',
            name='hostname_created',
            field=models.CharField(default='One-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='crfmetadata',
            name='hostname_created',
            field=models.CharField(default='One-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='labentry',
            name='hostname_created',
            field=models.CharField(default='One-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='requisitionmetadata',
            name='hostname_created',
            field=models.CharField(default='One-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='requisitionpanel',
            name='hostname_created',
            field=models.CharField(default='One-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
    ]
