language: python

python:
- 3.7

dist: xenial

sudo: true

services:
- mysql

addons:
  apt_packages:
  - libcups2-dev

branches:
  only:
  - develop

install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install flake8
- pip install -e .
- pip install coveralls

before_script:
- flake8 edc_metadata
- mysql -e 'create database edc character set utf8;'

script:
- coverage run --source=edc_metadata manage.py test

after_success:
- coveralls
