# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields
import django_revision.revision_field
import edc_base.model.fields.hostname_modification_field
import edc_base.model.fields.userfield
import edc_base.model.fields.uuid_auto_field
import edc_registration.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrfMetaData',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('schedule_name', models.CharField(max_length=25, null=True)),
                ('app_label', models.CharField(max_length=25, null=True)),
                ('model_name', models.CharField(max_length=25, null=True)),
                ('visit_code', models.CharField(max_length=25, null=True)),
                ('current_entry_title', models.CharField(max_length=250, null=True)),
                ('entry_status', models.CharField(choices=[('NEW', 'New'), ('KEYED', 'Keyed'), ('MISSED', 'Missed'), ('NOT_REQUIRED', 'Not required')], db_index=True, default='NEW', max_length=25)),
                ('due_datetime', models.DateTimeField(blank=True, null=True)),
                ('report_datetime', models.DateTimeField(blank=True, null=True)),
                ('entry_comment', models.TextField(blank=True, max_length=250, null=True)),
                ('close_datetime', models.DateTimeField(blank=True, null=True)),
                ('fill_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            bases=(edc_registration.model_mixins.RegisteredSubjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RequisitionMetaData',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('visit_code', models.CharField(max_length=25, null=True)),
                ('current_entry_title', models.CharField(max_length=250, null=True)),
                ('entry_status', models.CharField(choices=[('NEW', 'New'), ('KEYED', 'Keyed'), ('MISSED', 'Missed'), ('NOT_REQUIRED', 'Not required')], db_index=True, default='NEW', max_length=25)),
                ('due_datetime', models.DateTimeField(blank=True, null=True)),
                ('report_datetime', models.DateTimeField(blank=True, null=True)),
                ('entry_comment', models.TextField(blank=True, max_length=250, null=True)),
                ('close_datetime', models.DateTimeField(blank=True, null=True)),
                ('fill_datetime', models.DateTimeField(blank=True, null=True)),
                ('schedule_name', models.CharField(max_length=25, null=True)),
                ('app_label', models.CharField(max_length=25, null=True)),
                ('model_name', models.CharField(max_length=25, null=True)),
                ('panel_name', models.CharField(max_length=50, null=True)),
            ],
            bases=(edc_registration.model_mixins.RegisteredSubjectMixin, models.Model),
        ),
    ]
